name: m3u_baseUrl

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main
    paths:
      - ".github/workflows/m3u_baseUrl.yml"  # Change path if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${GITHUB_WORKSPACE}/requirements.txt  # If you have a requirements.txt file

    - name: Run Script
      run: python app.py  # Replace with your script's path

    - name: Add and commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Actions
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
        message: "chore: Update file"
        push: true  # Ensure push is correctly set to true
        github_token: ${{ secrets.PAT_TOKEN }}  # Use your personal access token (PAT) for authentication
