name: m3u_baseUrl

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/m3u_baseUrl.yml"  # change to be the path to this file

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${GITHUB_WORKSPACE}/requirements.txt  # if you have a requirements.txt file

    - name: Run script
      run: python app.py  # change to be the path to your script

    - name: Add and commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Actions
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
        message: "chore: Update file"
        push: true
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for authentication
